version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env         # aquí pones ES_BASE_URL, ES_API_KEY, etc.
    volumes:
      - backend_data:/app/data         # salida de runs (persistente)
      - ./backend:/app                 # hot-reload del código
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [appnet]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    environment:
      - VITE_API_BASE=http://backend:8080
      - VITE_HMR_HOST=192.168.2.5
    command: ["pnpm","dev","--","--host","0.0.0.0","--port","5173"]
    volumes:
      - ./frontend:/app                # hot-reload del código
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on: [backend]
    restart: unless-stopped
    networks: [appnet]

networks:
  appnet:

volumes:
  backend_data:
  frontend_node_modules:
